"""Regenerate every packaged identity asset from one native trefoil geometry.

Run from the repository root with::

    QT_QPA_PLATFORM=offscreen .venv/bin/python -m webjam_qt.theme.generate_brand_icons

The analytic curve in :mod:`webjam_qt.theme.brand` is canonical. This command
deterministically emits its SVG companion, Windows ICO, macOS ICNS, and Pocket
Stage asset catalog so no platform can silently drift to another logo.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

from PySide6.QtCore import QBuffer, QByteArray, QIODevice
from PySide6.QtGui import QImage, QPixmap
from PySide6.QtWidgets import QApplication

from webjam_qt.theme.brand import (
    BRAND_MARK_PATH,
    render_application_icon_pixmap,
    render_ios_application_icon_pixmap,
    trinity_svg_path_data,
)

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = BRAND_MARK_PATH.parent
IOS_ASSET_CATALOG = ROOT / "ios" / "PocketStage" / "Assets.xcassets"


def _png_from_pixmap(pixmap: QPixmap, *, opaque: bool = False) -> bytes:
    if pixmap.isNull():
        raise RuntimeError("Could not render WebJam brand icon")
    payload = QByteArray()
    buffer = QBuffer(payload)
    if not buffer.open(QIODevice.OpenModeFlag.WriteOnly):
        raise RuntimeError("Could not allocate icon output buffer")
    image = pixmap.toImage()
    if opaque:
        image = image.convertToFormat(QImage.Format.Format_RGB888)
    if not image.save(buffer, "PNG"):
        raise RuntimeError("Could not encode WebJam brand icon")
    buffer.close()
    return bytes(payload)


def _desktop_png(size: int) -> bytes:
    return _png_from_pixmap(render_application_icon_pixmap(size))


def _ios_png(size: int) -> bytes:
    return _png_from_pixmap(
        render_ios_application_icon_pixmap(size),
        opaque=True,
    )


def _svg_source() -> str:
    path_data = trinity_svg_path_data()
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <title>WebJam</title>
  <desc>One continuous three-loop trefoil for musicians playing together.</desc>
  <!--
    Generated from WebJam's canonical analytic trefoil. Do not edit this file
    directly; run python -m webjam_qt.theme.generate_brand_icons.
  -->
  <defs>
    <linearGradient id="webjam-warm-ribbon" x1="16%" y1="10%" x2="84%" y2="90%">
      <stop offset="0%" stop-color="#E87900"/>
      <stop offset="30%" stop-color="#F28A00"/>
      <stop offset="67%" stop-color="#F06A00"/>
      <stop offset="100%" stop-color="#BF5700"/>
    </linearGradient>
    <radialGradient id="webjam-node" cx="34%" cy="32%" r="68%">
      <stop offset="0%" stop-color="#F5A13A"/>
      <stop offset="42%" stop-color="#E87900"/>
      <stop offset="100%" stop-color="#E77600"/>
    </radialGradient>
  </defs>
  <path
    fill="none"
    stroke="url(#webjam-warm-ribbon)"
    stroke-width="4.86"
    stroke-linecap="round"
    stroke-linejoin="round"
    d="{path_data}"
  />
  <g fill="url(#webjam-node)">
    <circle cx="32" cy="9.28" r="4.22"/>
    <circle cx="52.86" cy="44.35" r="4.22"/>
    <circle cx="11.14" cy="44.35" r="4.22"/>
  </g>
  <g fill="#0A0A0A">
    <circle cx="32" cy="9.28" r="2.24"/>
    <circle cx="52.86" cy="44.35" r="2.24"/>
    <circle cx="11.14" cy="44.35" r="2.24"/>
  </g>
</svg>
"""


def _write_ico(path: Path) -> None:
    sizes = (16, 24, 32, 48, 64, 128, 256)
    images = [(size, _desktop_png(size)) for size in sizes]
    header = struct.pack("<HHH", 0, 1, len(images))
    offset = len(header) + (16 * len(images))
    directory = bytearray()
    payload = bytearray()
    for size, data in images:
        encoded_size = 0 if size == 256 else size
        directory.extend(
            struct.pack(
                "<BBBBHHII",
                encoded_size,
                encoded_size,
                0,
                0,
                1,
                32,
                len(data),
                offset,
            )
        )
        payload.extend(data)
        offset += len(data)
    path.write_bytes(header + directory + payload)


def _write_icns(path: Path) -> None:
    chunks = (
        (b"icp4", 16),
        (b"icp5", 32),
        (b"icp6", 64),
        (b"ic07", 128),
        (b"ic08", 256),
        (b"ic09", 512),
        (b"ic10", 1024),
    )
    body = bytearray()
    for kind, size in chunks:
        data = _desktop_png(size)
        body.extend(kind)
        body.extend(struct.pack(">I", len(data) + 8))
        body.extend(data)
    path.write_bytes(b"icns" + struct.pack(">I", len(body) + 8) + body)


def _write_json(path: Path, value: dict[str, object]) -> None:
    path.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _write_ios_assets(asset_catalog: Path, svg_source: str) -> None:
    app_icon = asset_catalog / "AppIcon.appiconset"
    brand_mark = asset_catalog / "WebJamMark.imageset"
    app_icon.mkdir(parents=True, exist_ok=True)
    brand_mark.mkdir(parents=True, exist_ok=True)
    _write_json(
        asset_catalog / "Contents.json",
        {"info": {"author": "xcode", "version": 1}},
    )
    _write_json(
        app_icon / "Contents.json",
        {
            "images": [
                {
                    "filename": "AppIcon-1024.png",
                    "idiom": "universal",
                    "platform": "ios",
                    "size": "1024x1024",
                }
            ],
            "info": {"author": "xcode", "version": 1},
        },
    )
    (app_icon / "AppIcon-1024.png").write_bytes(_ios_png(1024))
    _write_json(
        brand_mark / "Contents.json",
        {
            "images": [
                {
                    "filename": "webjam-mark.svg",
                    "idiom": "universal",
                }
            ],
            "info": {"author": "xcode", "version": 1},
            "properties": {"preserves-vector-representation": True},
        },
    )
    (brand_mark / "webjam-mark.svg").write_text(svg_source, encoding="utf-8")


def generate_brand_assets(
    *,
    desktop_output_dir: Path = OUTPUT_DIR,
    ios_asset_catalog: Path = IOS_ASSET_CATALOG,
) -> None:
    """Write all desktop and Pocket Stage assets from canonical geometry."""

    svg_source = _svg_source()
    desktop_output_dir.mkdir(parents=True, exist_ok=True)
    (desktop_output_dir / "webjam-mark.svg").write_text(
        svg_source,
        encoding="utf-8",
    )
    _write_ico(desktop_output_dir / "webjam.ico")
    _write_icns(desktop_output_dir / "webjam.icns")
    _write_ios_assets(ios_asset_catalog, svg_source)


def main() -> int:
    app = QApplication.instance() or QApplication([])
    generate_brand_assets()
    app.processEvents()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
